// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package transcribeservice

import (
	"github.com/aws/aws-sdk-go/private/protocol"
)

const (

	// ErrCodeBadRequestException for service response error code
	// "BadRequestException".
	//
	// Your request didn't pass one or more validation tests. This can occur when
	// the entity you're trying to delete doesn't exist or if it's in a non-terminal
	// state (such as IN PROGRESS). See the exception message field for more information.
	ErrCodeBadRequestException = "BadRequestException"

	// ErrCodeConflictException for service response error code
	// "ConflictException".
	//
	// A resource already exists with this name. Resource names must be unique within
	// an Amazon Web Services account.
	ErrCodeConflictException = "ConflictException"

	// ErrCodeInternalFailureException for service response error code
	// "InternalFailureException".
	//
	// There was an internal error. Check the error message, correct the issue,
	// and try your request again.
	ErrCodeInternalFailureException = "InternalFailureException"

	// ErrCodeLimitExceededException for service response error code
	// "LimitExceededException".
	//
	// You've either sent too many requests or your input file is too long. Wait
	// before retrying your request, or use a smaller file and try your request
	// again.
	ErrCodeLimitExceededException = "LimitExceededException"

	// ErrCodeNotFoundException for service response error code
	// "NotFoundException".
	//
	// We can't find the requested resource. Check that the specified name is correct
	// and try your request again.
	ErrCodeNotFoundException = "NotFoundException"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{
	"BadRequestException":      newErrorBadRequestException,
	"ConflictException":        newErrorConflictException,
	"InternalFailureException": newErrorInternalFailureException,
	"LimitExceededException":   newErrorLimitExceededException,
	"NotFoundException":        newErrorNotFoundException,
}
