// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package lexruntimeservice

const (

	// ErrCodeBadGatewayException for service response error code
	// "BadGatewayException".
	//
	// Either the Amazon Lex bot is still building, or one of the dependent services
	// (Amazon Polly, AWS Lambda) failed with an internal service error.
	ErrCodeBadGatewayException = "BadGatewayException"

	// ErrCodeBadRequestException for service response error code
	// "BadRequestException".
	//
	// Request validation failed, there is no usable message in the context, or
	// the bot build failed.
	ErrCodeBadRequestException = "BadRequestException"

	// ErrCodeConflictException for service response error code
	// "ConflictException".
	//
	// Two clients are using the same AWS account, Amazon Lex bot, and user ID.
	ErrCodeConflictException = "ConflictException"

	// ErrCodeDependencyFailedException for service response error code
	// "DependencyFailedException".
	//
	// One of the downstream dependencies, such as AWS Lambda or Amazon Polly, threw
	// an exception. For example, if Amazon Lex does not have sufficient permissions
	// to call a Lambda function which results in AWS Lambda throwing an exception.
	ErrCodeDependencyFailedException = "DependencyFailedException"

	// ErrCodeInternalFailureException for service response error code
	// "InternalFailureException".
	//
	// Internal service error. Retry the call.
	ErrCodeInternalFailureException = "InternalFailureException"

	// ErrCodeLimitExceededException for service response error code
	// "LimitExceededException".
	ErrCodeLimitExceededException = "LimitExceededException"

	// ErrCodeLoopDetectedException for service response error code
	// "LoopDetectedException".
	//
	// Lambda fulfilment function returned DelegateDialogAction to Amazon Lex without
	// changing any slot values.
	ErrCodeLoopDetectedException = "LoopDetectedException"

	// ErrCodeNotFoundException for service response error code
	// "NotFoundException".
	//
	// Resource (such as the Amazon Lex bot or an alias) referred is not found.
	ErrCodeNotFoundException = "NotFoundException"
)
